- name: Install snmpd & play 2048
  hosts: all
  become: true
  become_user: root
  # vars:
    # sshgroup_name: sshusers
    # user:
      # login: deploy
      # password_hash:
        # "$6$NwI7op8FHR1VQta6$zuQXHtNtM/7SRQsf1./18WbBrHMq4mT88nWh67ThmlWcqyVX3F\
        # BTY9uj/07tR9ViDEvjg6/bh0y3mSjeDQYe3."
      # authorized_key:
        # "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr\
        # +kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6I\
        # edplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2\
        # hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZE\
        # nDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHln\
        # VYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key"
  tasks: 
    - name: Add docker repository
      yum_repository:
        name: docker
        description: EPEL YUM repo
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    - name: Install docker
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
    - name: Start docker
      systemd:
        name: docker
        enabled: true
        state: started
    - name: Create a webserver container
      community.docker.docker_container:
        name: web
        image: zanatar/webserver
        ports:
        - "8080:9000"
        hostname: test.localdomain 
