pipeline {
    agent any
    environment {
        DOCKER_USER = credentials('DOCKER_ID')
        DOCKER_PASS = credentials('DOCKER_PASS')
    }
    stages {
        stage('test') {
            steps {
                sh "cd webserver/student_exam2"
                sh "pip3 install -e '.[test]'"
				sh "coverage run -m pytest"
				sh "coverage report"
            }
		}
		stage('build') {
			steps {
				sh "docker login -u '${DOCKER_USER}' -p '${DOCKER_PASS}'"
				sh "docker build -t zanatar/webserver:latest ../."
				sh "docker push zanatar/webserver:latest"
			}
		}
    }  
}